name: Python Test2
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Repodan bütün dosyaları al
      uses: actions/checkout@v4

    - name: Python 3.8 yükle
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Test sonucunu yorumla
      run: |
            ls > deneme.txt
            cat deneme.txt