name: Python Test3
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Repodan bütün dosyalari al
      uses: actions/checkout@v2

    - name: Sonuçlari raporla
      run: |
            echo "Test işlemi başarili"
            echo "CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}"
            echo "SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}"
            echo "PROJECT_ID: ${{ secrets.PROJECT_ID }}"